services:
  currency-database:
    container_name: currency-database
    platform: linux/amd64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '4307:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d
  
  currency-php:
    container_name: currency-php
    platform: linux/amd64
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    ports:
      - '9001:9000'
    volumes:
      - ./:/var/www/currency-api
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - currency-database
  
  currency-nginx:
    container_name: currency-nginx
    platform: linux/amd64
    image: nginx:latest
    ports:
      - '8001:80'
      - '443:443'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/currency-api
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - currency-php
  
  currency-mailer:
    image: schickling/mailcatcher
    ports: [ '1025', '1080' ]
  
  currency-phpmyadmin:
    container_name: currency-pma
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    links:
      - currency-database
    environment:
      PMA_HOST: currency-database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - '93:80'
    depends_on:
      - currency-database
      - currency-php
      - currency-nginx
volumes:
  db_data: