name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
          MYSQL_USER: ${{ secrets.DB_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    env:
      DATABASE_URL: mysql://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@127.0.0.1:3306/${{ secrets.DB_DATABASE }}
      REDIS_URL: redis://127.0.0.1:6379
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl, pdo_mysql, redis

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Create test database
        run: |
              mysql \
                -uroot -p${{ secrets.DB_PASSWORD }} -h127.0.0.1 -e "
                  CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_DATABASE }}_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
                  GRANT ALL PRIVILEGES ON ${{ secrets.DB_DATABASE }}_test.* TO '${{ secrets.DB_USERNAME }}'@'%';
                  FLUSH PRIVILEGES;
              "

      - name: Run migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction

      - name: Run tests
        run: ./vendor/bin/phpunit --coverage-text
